services:
  eikona.media.purge_media_files.command.purge_media_files:
    class: EikonaMedia\Akeneo\PurgeMediaFilesBundle\Command\PurgeMediaFilesCommand
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@akeneo_file_storage.repository.file_info'
      - '%catalog_storage_dir%'
      - '@akeneo_file_storage.file_storage.filesystem_provider'
      - '@pim_catalog.repository.product'
      - '@pim_catalog.repository.product_model'
    tags:
      - { name: console.command, command: 'eikona-media:media:purge-files' }
